spring:
  application:
    name: api-order
  cloud:
    nacos:
      discovery:
        server-addr: 152.136.62.136:8848
        username: nacos
        password: nacos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.62.136:3306/api_order
    username: root
    password: 1481148515Gjh.
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  redis:
    database: 1
    host: 152.136.62.136
    port: 6379
    password: 123456
    timeout: 5000
  rabbitmq:
    host: 47.113.177.68
    port: 5672
    username: guest
    password: guest
    virtualHost: /

server:
  port: 9001
  servlet:
    context-path: /api/order
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 0 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 1 # 逻辑未删除值（默认为 0）

dubbo:
  application:
    name: dubbo
    qosEnableL: true
    qosPort: 33331
    qsosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://152.136.62.136:8848
