# 公共配置文件
spring:
  application:
    name: api-backend
  cloud:
    nacos:
      discovery:
        server-addr: 152.136.62.136:8848
        username: nacos
        password: nacos
    stream:
      binders:
        defaultRabbit:
          type: rabbit
      bindings:
        output:
          destination: studyExchange
          content-type: application/json
          binder: defaultRabbit
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://152.136.62.136:3306/api_backend
    username: root
    password: 1481148515Gjh.
  # Redis 配置
  redis:
    database: 1
    host: 152.136.62.136
    port: 6379
    password: 123456
    timeout: 5000
  rabbitmq:
    host: 47.113.177.68
    port: 5672
    username: guest
    password: guest
    virtualHost: /
    #确认消息已发送到交换机(Exchange)
    publisher-confirm-type: correlated
    #确认消息已发送到队列(Queue)
    publisher-returns: true
    listener:
      simple:
        # 确定机制
        acknowledge-mode: manual

server:
  port: 8080
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
        #cookie作用域
#        domain: #
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 0 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 1 # 逻辑未删除值（默认为 0）


dubbo:
  application:
    name: dubbo
    qosEnableL: true
    qosPort: 33333
    qosAcceptForeignIp: false
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://152.136.62.136:8848
    username: nacos
    password: nacos
